<?php

namespace Homesoft\ExternalDiskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExternalDiskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalDiskRepository extends EntityRepository
{
}
