homesoft_media:
    resource: "@HomesoftMediaBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

homesoft_platform_files:
    resource: "@HomesoftExternalDiskBundle/Resources/config/routing.yml"
    prefix:   /