# app/config/routing.yml

homesoft_platform_files:
    resource: "@HomesoftPlatformFilesBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"