homesoft_external_disk_homepage:
    path:     /
    defaults: { _controller: HomesoftExternalDiskBundle:Default:index }

homesoft_get_external_disk:
    path:   /externals-disks
    defaults: { _controller: HomesoftExternalDiskBundle:Default:getExternalsDisks }