homesoft_platform_files_homepage:
    path:     /
    defaults: { _controller: HomesoftPlatformFilesBundle:Files:index }

homesoft_platform_files_get_files:
    path:   /get
    defaults: { _controller: HomesoftPlatformFilesBundle:Files:getFiles }
    options:
        expose: true
    requirements:
        methods: POST

homesoft_platform_files_link_file:
    path: /link
    defaults: { _controller: HomesoftPlatformFilesBundle:Files:linkFile }
    options:
        expose: true

homesoft_platform_files_cmd_ctrl:
    path: /cmd-ctrl-file/{cmdCtrlVideo}
    defaults: { _controller: HomesoftPlatformFilesBundle:Files:cmdCtrlFile }
    options:
        expose: true
    requirements:
        methods: GET