homesoft_platform_files_homepage:
    path:     /
    defaults: { _controller: HomesoftPlatformFilesBundle:Files:index }

homesoft_platform_files_get_files:
    path:   /get-files
    defaults: { _controller: HomesoftPlatformFilesBundle:Files:getFiles }
    options:
        expose: true
    requirements:
        methods: POST

homesoft_platform_files_play_file:
    path: /play-file
    defaults: { _controller: HomesoftPlatformFilesBundle:Files:playFile }
    options:
        expose: true
    requirements:
        methods: POST

homesoft_platform_files_stop_file:
    path: /stop-file
    defaults: { _controller: HomesoftPlatformFilesBundle:Files:stopFile }
    options:
        expose: true
