homesoft_platform_files_homepage:
    path:     /
    defaults: { _controller: HomesoftPlatformFilesBundle:Default:index }

homesoft_platform_files_get_files:
    path:   /files
    defaults: { _controller: HomesoftPlatformFilesBundle:Default:getFiles }
    requirements:
        methods: POST
    options:
        expose: true

homesoft_platform_files_get_remotes:
    path:   /remotes
    defaults: { _controller: HomesoftPlatformFilesBundle:Default:getRemotes }
    requirements:
        methods: GET
    options:
        expose: true

