homesoft_platform_files_homepage:
    path:     /
    defaults: { _controller: HomesoftPlatformFilesBundle:Files:index }

homesoft_platform_files_view:
    path:     /{remote}
    defaults: { _controller: HomesoftPlatformFilesBundle:Files:view }

homesoft_platform_files_get_files:
    path:   /{pathRemote}/get-files
    defaults: { _controller: HomesoftPlatformFilesBundle:Files:getFiles }
    options:
        expose: true
