services:
    homesoft_platform_files.remote_scanner:
        class: Homesoft\PlatformFilesBundle\services\RemoteScanner
    homesoft_platform_files.system_scanner:
        class: Homesoft\PlatformFilesBundle\services\SystemScanner